apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-data-pvc
  namespace: daily-quote
  labels:
    app: daily-quote
    component: api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quotes-files-pvc
  namespace: daily-quote
  labels:
    app: daily-quote
    component: api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
